-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1:3306
-- Tiempo de generación: 21-08-2023 a las 16:31:39
-- Versión del servidor: 8.0.31
-- Versión de PHP: 8.0.26

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `proyecto-utn`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `recetas`
--

DROP TABLE IF EXISTS `recetas`;
CREATE TABLE IF NOT EXISTS `recetas` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `imagen_ID` varchar(60) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `titulo` varchar(60) NOT NULL,
  `minutos` int NOT NULL,
  `porciones` int NOT NULL,
  `ingredientes` text NOT NULL,
  `preparacion` text NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=36 DEFAULT CHARSET=utf8mb3;

--
-- Volcado de datos para la tabla `recetas`
--

INSERT INTO `recetas` (`ID`, `imagen_ID`, `titulo`, `minutos`, `porciones`, `ingredientes`, `preparacion`) VALUES
(1, 'vmy8xhdrgndo0lpei4fj', 'Matambre a la pizza', 150, 4, '<li>1 litro de leche</li>\r\n<li>1 matambre de 700 gr. a 1 kg.</li>\r\n<li>1 cubito de caldo de verduras</li>                  \r\n<li>1 taza de salsa de tomate</li>\r\n<li>250 gr. de mozzarella</li>\r\n<li>1 cebolla</li>\r\n<li>1/2 pimiento rojo</li>\r\n<li>150 gr. de jamon en fetas</li>\r\n<li>6 dientes de ajo</li>\r\n<li>150 gr. de aceitunas</li>\r\n<li>Sal, pimienta, ajo en polvo, ají molido, orégano</li>', '<li>Desgrasar el matambre lo máximo posible y ponerlo en una olla con la leche, el caldo de verduras, sal, pimienta, ají molido y 4 dientes de ajo. Dejar a fuego bajo por 2 horas. Este es el secreto para que el matambre a la pizza quede tierno, tan tierno que se deshace!</li><br>\r\n\r\n<li>Picar la cebolla, el pimiento rojo y los ajos. Saltear en una sartén con aceite de oliva. Agregar la salsa de tomate. Salpimentar y condimentar con ají molido y orégano. Reservar.</li><br>\r\n\r\n<li>Una vez que el matambre esté listo, tirarlo a la parrilla por unos 5 minutos. Agregar el tuco, la mozzarella y las fetas de jamón. Dejarlo en la parrilla hasta que se derrita la mozzarella.</li><br>\r\n\r\n<li>Al sacarlo de la parrilla finalizar con las aceitunas y orégano espolvereado por encima.</li>'),
(2, 'zs9pvbsndywlszevquwd', 'Pastel de papas', 60, 3, '<li>1 kg. de papas</li>\r\n<li>1/2 kg. de carne picada</li>\r\n<li>1 pimiento rojo</li>\r\n<li>1 cebolla</li>\r\n<li>2 dientes de ajo</li>\r\n<li>1 cubito de caldo de carne</li>\r\n<li>Ajo en polvo, pimentón, pimienta, sal</li>\r\n<li>1 cucharada de manteca</li>\r\n<li>1 chorrito de leche</li>\r\n<li>2 huevos</li>\r\n<li>100 gr. de aceitunas</li>', '<li>Cortar las papas en cubos y ponerlas a hervir con sal.</li><br>\r\n\r\n<li>Picar la cebolla, el ajo y el pimiento rojo. Sofreír en una olla o sartén</li><br>\r\n\r\n<li>Cuando la cebolla está transparente, agregar la carne y sofreírla mientras se deshace con una cuchara.</li><br>\r\n\r\n<li>Salpimentar, agregar el cubito de caldo, el ajo en polvo, el pimentón y cocer la carne 15min.</li><br>\r\n\r\n<li>Una vez que las patatas estén hervidas, hacer en caliente un puré con la manteca y la leche. Salpimentar.</li><br>\r\n\r\n<li>Agregar al relleno los huevos picados y las aceitunas.</li><br>\r\n\r\n<li>Poner en una fuente para horno una base de puré, agregar por encima la carne (dejar que se entibie un poco) y colocar otra capa de puré. Para distribuirlo, se moja la cuchara con agua.</li><br>\r\n\r\n<li>Llevar a horno fuerte unos 15-20 min. o hasta que la parte de arriba esté crocante.</li>'),
(3, 'nkod7wakon1381etuipu', 'Pollo Marsala', 40, 3, '<li>4 pechugas de pollo cortadas</li>\r\n<li>1 cucharada de harina</li>\r\n<li>Aceite de oliva</li>\r\n<li>1 cucharada de manteca</li>\r\n<li>4 dientes de ajo</li>\r\n<li>300 gr. de champiñones cortados</li>\r\n<li>3/4 tazas de vino Marsala</li>\r\n<li>3/4 tazas de caldo de pollo</li>\r\n<li>Perejil</li>\r\n<li>Sal y pimienta a gusto</li>', '<li>Dividir cada pechuga en 2 partes y salpimentar. Con un martillo ablandador, golpear las pechugas para que alcancen el mismo grosor en todas sus partes y al mismo tiempo conseguir un bocado más tierno. Enharinar las pechugas de pollo.</li><br>\r\n\r\n<li>En una sartén con un chorro de aceite de oliva y la cucharada de manteca, sofreír las pechugas aproximadamente 3 minutos por cada lado. Tienen que quedar doradas por fuera. Reservar.</li><br>\r\n\r\n<li>En el mismo aceite saltear los ajos previamente picados.</li><br>\r\n\r\n<li>Cuando los ajos empiecen a dorarse añadir los champiñones y cocinar durante un par de minutos.</li><br>\r\n\r\n<li>Luego agregar la harina y revolver constantemente para evitar grumos.</li><br>\r\n\r\n<li>Incorporar el vino marsala a la cazuela. Subir el fuego para que se evapore el alcohol.</li><br>\r\n\r\n<li>Añadir las pechugas de pollo y el caldo de pollo. Cocinar a fuego suave durante 10 minutos aproximadamente.</li><br>\r\n\r\n<li>Picar unas hojas de perejil. Espolvorear por encima del pollo justo antes de servir.</li>\r\n'),
(8, 'iqzbjxrhootqylewn8ra', 'Empanadas de carne', 50, 3, '<li>12 tapas de empanadas</li>\r\n<li>500 gr. de roast beef o bola de lomo</li>\r\n<li>2 cebollas</li>\r\n<li>2 dientes de ajo</li>\r\n<li>1/2 morrón rojo</li>\r\n<li>2 cucharadas de puré de tomates</li>\r\n<li>100 gr. de aceitunas</li>\r\n<li>3 huevos</li>\r\n<li>1 papa grande</li>\r\n<li>Sal, pimienta negra, pimentón y comino</li>', '<li>En una olla con aceite caliente agregar la cebolla y el morrón. Dejar dorar unos minutos y cuando la cebolla este transparente, agregar el ajo, un poco de sal y pimienta.</li><br>\r\n\r\n<li>Subir el fuego y agregar la carne previamente cortada en cuadraditos. Mover la carne para que no quede pegada.</li><br>\r\n\r\n<li>Cuando la carne esté sellada agregar las 2 cucharadas de puré de tomates. Condimentar con pimenton, comino, un poco más de sal, pimienta negra y mezclar bien todo. Tapar (no del todo, dejar un pequeño hueco) y dejar cocinar media hora revolviendo de a poco.</li><br>\r\n\r\n<li>Mientras dejamos cocinando el relleno, hervimos los 3 huevos y la papa grande cortada en cubitos.</li><br>\r\n\r\n<li>Sacar del fuego el relleno y dejar enfriar en la olla.</li><br>\r\n\r\n<li>Una vez frio, agregar las papas, las aceitunas y los huevos picados.</li><br>\r\n\r\n<li>Repartir el relleno en las tapas de empanada, y cerrar con un repulgue tradicional.</li><br>\r\n\r\n<li>Poner nuestras empanadas de carne en una placa y llevar a horno fuerte hasta que estén doradas y a disfrutar!</li>\r\n'),
(9, 'uuxcxmufhyvpwsn4jqbh', 'Pizza de jamón y queso', 70, 3, 'Para la masa:\r\n<li>500 gr. de harina 000</li>\r\n<li>25 gr. de levadura fresca</li>\r\n<li>1/2 cucharada de sal</li>\r\n<li>1 cucharada de azúcar</li>\r\n<li>4 cucharadas de aceite de oliva</li>\r\n<li>1 taza de agua tibia</li><br>\r\n\r\nPara la cobertura:\r\n<li>100 gr. de jamón</li>\r\n<li>100 gr. de mozzarella</li>\r\n<li>250 gr. de tomate triturado</li>\r\n<li>80 gr. de aceitunas</li>\r\n<li>Sal y pimienta negra</li>\r\n<li>Orégano</li>', '<li>Para la masa, en un bol o taza colocar la levadura, media taza de agua tibia y agregar la cucharada de azúcar. Mezclar bien hasta que se formen burbujitas. Tapar con un nylon y dejar levar mas o menos 10 minutos.</li><br>\r\n\r\n<li>En otro bol, colocar la harina y mezclarla con la sal. Hacer un hueco en el centro, y luego volcar la media taza de agua con la levadura e incorporar el resto del agua tibia.</li><br>\r\n\r\n<li>Unir con las manos todos los ingredientes hasta formar una masa. Agregar en forma de hilo el aceite y volver a amasar.</li><br>\r\n\r\n<li>Dejar descansar la masa unos 15 minutos, y luego amasarla en una mesa con harina. Dividir la masa en dos bollos del mismo tamaño.</li><br>\r\n\r\n<li>Estirar la masa hasta lograr un círculo. Poner la masa en una fuente para pizza y dejar descansar hasta que leve un poquito. Aproximadamente 15 minutos.</li><br>\r\n\r\n<li>Llevar a horno fuerte unos 6 minutos. Esto es muy importante para que la masa quede bien cocida.</li><br>\r\n\r\n<li>Agregar el tomate triturado hasta cubrir toda la superficie y llevar al horno 2 minutos más.</li><br>\r\n\r\n<li>Añadir el jamón y la mozzarella bien distribuida a lo largo de la pizza.</li><br>\r\n\r\n<li>Retirar una vez que la mozzarella se haya derretido y espolvorear con orégano y las aceitunas.</li>'),
(10, 'casiq7im7lx1gywawxwq', 'Ensalada César', 30, 2, 'Para la salsa:\r\n<li>1 yema de huevo</li>\r\n<li>Jugo de medio limón</li>\r\n<li>1 diente de ajo</li>\r\n<li>1 cucharadita de mostaza</li>\r\n<li>3 anchoas</li>\r\n<li>2 cucharadas de queso parmesano rallado</li>\r\n<li>Sal, pimienta y aceite</li><br>\r\n\r\nPara la ensalada:\r\n<li>1 pechuga de pollo</li>\r\n<li>1 pedacito de queso parmesano</li>\r\n<li>1 lechuga (a gusto el tipo)</li>\r\n<li>2 huevos</li>\r\n<li>100 gr. de tomates cherrys</li>\r\n<li>50 gr. de aceitunas (opcional)</li>\r\n<li>2 rodajas de pan de molde (pan lactal)</li>\r\n<li>Sal y pimienta</li>', '<li>Lavar la lechuga y cortarla con la mano en trozos grandes.</li><br\r\n\r\n<li>Poner una olla a hervir con agua y, una vez que esté hirviendo, colocar los huevos en ella. Dejar hervir por 7 minutos. Sacar del fuego y colocar los huevos en agua fría. Reservar.</li><br>\r\n\r\n<li>Cortar la pechuga de pollo en tiras de 1 cm. aproximadamente y cocinarlas en una sartén con un poco de aceite hasta que estén doradas de ambos lados. Reservar.</li><br>\r\n\r\n<li>Quitarle los bordes al pan y cortar en cuadraditos pequeños.</li><br>\r\n\r\n<li>Ponerlos en una sartén caliente hasta que estén dorados de ambas partes y crujientes.</li><br>\r\n\r\n<li>Para la salsa César colocar las anchoas con el ajo en un bol y machacar hasta que quede una pasta.</li><br>\r\n\r\n<li>En un bol aparte, batir la yema con la mostaza e integrar. Agregar la pasta de anchoa y ajos hasta que esté bien unida.</li><br>\r\n\r\n<li>Salpimentar e ir agregando el aceite en forma de hilo y batiendo enérgicamente hasta que espese. Agregar por último el parmesano rallado. Este proceso puede hacerse con mixer.</li><br>\r\n\r\n<li>Armar la ensalada: colocar en una fuente la lechuga, por encima, el pollo, el pan, los huevos, las aceitunas y los tomates cherrys. Bañar con la salsa César.</li>'),
(11, 'e6njonl5ybemh0tinbhp', 'Ñoquis de calabaza', 90, 3, 'Para los ñoquis:\r\n<li>800 gr. de calabaza</li>\r\n<li>250 gr. de harina</li>\r\n<li>1 yema de huevo</li>\r\n<li>Sal, pimienta negra y aceite de oliva</li><br>\r\n\r\nPara la salsa:\r\n<li>1/2 cebolla</li>\r\n<li>1 diente de ajo</li>\r\n<li>500 gr. de carne picada</li>\r\n<li>1 trozo de morrón rojo</li>\r\n<li>1 tomate</li>\r\n<li>1 chorro de vino</li>\r\n<li>1 lata de puré de tomates</li>\r\n<li>1 taza de caldo</li>\r\n<li>Orégano</li>\r\n<li>Laurel</li>\r\n<li>Sal, pimienta negra y aceite de oliva</li>', '<li>Para la salsa, picar la cebolla, el ajo y el morrón.</li><br>\r\n\r\n<li>Dorar en aceite de oliva hasta que la cebolla esté transparente. Agregar el tomate picado y saltear un par de minutos.</li><br>\r\n\r\n<li>Agregar la carne picada. Ir deshaciendo con una cuchara de madera. Remover continuamente hasta que la carne esté hecha completamente separada y haya cambiado de color.</li><br>\r\n\r\n<li>Agregar el chorro de vino y cocinar unos 2 minutos hasta que se evapore el alcohol.</li><br>\r\n\r\n<li>Agregar la sal, pimienta, orégano (solo un poquito) y la hoja de laurel. Incorporar el puré de tomates y el caldo. Revolver y tapar.</li><br>\r\n\r\n<li>Dejar hervir a fuego medio entre 30 y 45 minutos.</li><br>\r\n\r\n<li>Mientras dejamos que se cocine la salsa, vamos a ir haciendo la masa para los ñoquis.</li><br>\r\n\r\n<li>Cocinar la calabaza de cualquier manera que no sea hervida, puede ser al horno, al vapor o al microondas. No debe ser hervida así no absorbe agua. Debe quedar lo más seca posible.</li><br>\r\n\r\n<li>Hacer un puré de calabaza y cuando esté tibio agregar la yema, la sal, la pimienta y la harina tamizada. Unirlo hasta conseguir un bollo bien homogéneo.</li><br>\r\n\r\n<li>Formar choricitos y darle la forma a los ñoquis con un tenedor o una ñoquera enharinada.</li><br>\r\n\r\n<li>Hervir por unos minutos hasta que floten.</li><br>\r\n\r\n<li>Colocar en una fuente con una capa de salsa en la base, luego ponerle el resto de la salsa por encima y a comer!</li>'),
(12, 't9srhknbqtwfkfekarwm', 'Tortilla de papas', 50, 3, '<li>4 huevos</li>\r\n<li>3 papas medianas</li>\r\n<li>1/2 cebolla</li>\r\n<li>Sal</li>\r\n<li>Aceite</li>', '<li>Cortar las papas en rodajas finas, estilo papas españolas. Deben ser de tamaño mediano, ya que queremos que queden bien unidas con el huevo.</li><br>\r\n\r\n<li>Colocar abundante aceite en una sartén. Poner la sartén a fuego fuerte y en cuanto esté tibio el aceite vamos a agregar todas las papas. Ese es el primer truco, agregar las papas antes de que el aceite esté hirviendo. Las dejamos cocinar durante 5 minutos.</li><br>\r\n\r\n<li>Mientras tanto vamos a cortar la cebolla en julianas. Una vez pasados los 5 minutos agregamos las cebollas a la sartén con las papas, revolviendo suavemente.</li><br>\r\n\r\n<li>Luego de revolver bien para que esté todo integrado en la sartén, agregamos un poco de sal y vamos a bajar el fuego al mínimo y vamos a tapar la sartén. Pero la vamos a tapar sin que quede totalmente cerrada, dejando una mínima abertura para que pueda salir el vapor. Así la dejamos durante 15-20 minutos mientras de vez en cuando vamos revolviendo suave y procurando que no se pegue.</li><br>\r\n\r\n<li>Una vez que las papas estén cocidas, vamos a proceder a colarlas, dejándolas en un colador hasta que baje todo el aceite.</li><br>\r\n\r\n<li>Colocar los 4 huevos en un bol con un poco de sal y batirlos bien durante unos minutos.</li><br>\r\n\r\n<li>Agregar las papas con cebollas al bol y volver a batir hasta que esté todo integrado y unido.</li><br>\r\n\r\n<li>Agregamos un chorro de aceite en una sartén a fuego fuerte.</li><br>\r\n\r\n<li>Cuando esté bien caliente el aceite, agregamos la mezcla que tenemos en el bol y movemos la sartén agitándola durante 30 segundos. Lo que estamos haciendo es cuajar los huevos para que la tortilla española quede a la perfección.</li><br>\r\n\r\n<li>Luego de los 30 segundos vamos a poner el fuego bajo y con una espátula vamos a ir corrigiendo los bordes mientras se va cociendo. Vamos a cocinar la tortilla española así durante 5 minutos.</li><br>\r\n\r\n<li>Luego vamos a darla vuelta. Para ésto vamos a colocar un plato encima de la sartén y la damos vuelta sin miedo. Una vez que la damos vuelta vamos a emprolijar los bordes nuevamente con la espátula y dejamos cocer unos 3-4 minutos más.</li><br>\r\n\r\n<li>Para sacarla vamos a volver a darla vuelta. Es decir, colocamos nuevamente el plato encima de la sartén como hicimos en el punto anterior y lo damos vuelta con cuidado. Buen provecho!</li>'),
(4, 'qepjwzvpqathv8zjd8yc', 'Risotto de hongos', 60, 4, '<li>450 gr. de hongos</li>\r\n<li>350 gr. de arroz arborio</li>\r\n<li>1 cebolla</li>\r\n<li>2 dientes de ajo</li>\r\n<li>1 taza de vino blanco</li>\r\n<li>6 tazas de caldo de verduras</li>\r\n<li>75 gr. de manteca</li>\r\n<li>75 gr. de queso parmesano rallado</li>\r\n<li>Sal y pimienta</li>\r\n<li>Perejil </li>', '<li>Saltear en una sartén los dos dientes de ajo con la cebolla picada hasta que esten transparentes.</li><br>\r\n\r\n<li>Sumar los hongos laminados (previamente limpiados) con una pizca de sal, revolver unos minutos.</li><br>\r\n\r\n<li>Añadir el arroz y continuar la cocción durante 2 a 3 minutos hasta que los bordes del arroz comiencen a verse transparentes.</li><br>\r\n\r\n<li>Agregar la copa de vino y subir el fuego para que se evapore el alcohol.</li><br>\r\n\r\n<li>Añadir 1 taza de caldo y una vez que se haya absorbido el líquido repetir la operación con el caldo restante.</li><br>\r\n\r\n<li>Incorporar la manteca y el queso, mezclar hasta que la manteca se funda, salpimentar y servir decorado perejil y más queso parmesano.</li>\r\n'),
(5, 'b8xduqos0tssklfmuggo', 'Sopa de verduras', 40, 4, '<li>3 dientes de ajo</li>\r\n<li>1 cebolla</li>\r\n<li>2 zanahorias</li>\r\n<li>1/2 calabaza</li>\r\n<li>2 choclos</li>\r\n<li>1 apio</li>\r\n<li>1 puerro</li>\r\n<li>2 cubitos de caldo de verduras</li>\r\n<li>1 litro de agua</li>', '<li>Lavamos muy bien todas las verduras que vamos a emplear en esta sopa.</li><br>\r\n\r\n<li>Cortamos todas las verduras menos el choclo y la calabaza en juliana y reservamos en un bol.</li><br>\r\n\r\n<li>En una olla grande ponemos a hervir el agua y colocamos los cubitos de caldo.</li><br>\r\n\r\n<li>Una vez entrado en hervor añadimos todas las verduras que hemos cortado en juliana junto al choclo y la calabaza.</li><br>\r\n\r\n<li>Cocemos a fuego moderado durante unos 30 minutos, con la olla un poco tapada. Durante ese tiempo no hace falta remover la sopa.</li><br>\r\n\r\n<li>Servimos muy caliente en un plato hondo. Podemos espolvorear con un poco de perejil picado.</li>'),
(6, 'p3kertierxljmq9evofh', 'Sorrentinos de j&q', 70, 4, 'Para la masa:\r\n<li>100 gr. de harina de trigo de todo uso</li>\r\n<li>100 gr. de sémola fina de trigo</li>\r\n<li>2 huevos medianos</li>\r\n<li>Sal</li><br>\r\n\r\nPara el relleno:\r\n<li>200 gr. de jamón cocido</li>\r\n<li>150 gr. de mozzarella (u otro queso)</li>\r\n<li>Pimienta negra</li><br>\r\n\r\nPara la salsa:\r\n<li>1 cebolla</li>\r\n<li>2 dientes de ajo</li>\r\n<li>500 gr. de tomate triturado</li>\r\n<li>250 gr. de carne picada</li>\r\n<li>Sal, pimienta negra, pimentón y ají en polvo</li>', '<li>Para la masa, en un bol poner la harina y la sémola, hacer un agujero en el medio, echar los huevos y una pizca de sal.</li><br>\r\n\r\n<li>Mezclar y amasar unos 5 minutos, dejar reposar.</li><br>\r\n\r\n<li>Para el relleno, en un bol colocar el jamón cocido picado, y la mozzarella, añadir un poco de pimienta y mezclar.</li><br>\r\n\r\n<li>Formar 20 bolas de relleno de 25 gr. cada una.</li><br>\r\n\r\n<li>Retomando la masa, dividir la pasta en 4 partes y estirarla con el rodillo o la máquina.</li><br>\r\n\r\n<li>Marcar una lámina de pasta con el cortador y colocar una bola de relleno en cada marca.</li><br>\r\n\r\n<li>Humedecer los bordes, forrar con otra lámina, aplastar un poco y cortarlos, repetir hasta formarlos todos y reservar.</li><br>\r\n\r\n<li>Para la salsa, sofreír los dientes de ajo y la cebolla bien picada hasta que tome un color transparente.</li><br>\r\n\r\n<li>Agregar la carne picada con una pizca de sal, pimienta negra, pimentón y ají en polvo hasta que empiece a tomar color.</li><br>\r\n\r\n<li>Añadir la salsa y cocinar unos 30 minutos.</li><br>\r\n\r\n<li>Mientras la salsa se cocina, colocar en una olla 1 litro de agua con sal hasta que rompa en hervor.</li><br>\r\n\r\n<li>Hervir los sorrentinos unos 3 o 4 minutos.</li><br>\r\n\r\n<li>Mezclarlos con la salsa y servir!</li>'),
(7, 'jm2zrwlmqjfflmudvhto', 'Guiso de lentejas', 90, 5, '<li>350 gr. de lentejas</li>\r\n<li>1 chorizo colorado</li>\r\n<li>150 gr. de panceta ahumada</li>\r\n<li>1 cebolla grande</li>\r\n<li>1/2 morrón rojo</li>\r\n<li>1 papa grande</li>\r\n<li>500 gr. de tomate triturado</li>\r\n<li>2 dientes de ajo</li>\r\n<li>2 hojas de laurel</li>\r\n<li>Sal, pimienta negra, pimentón, ají en polvo y orégano</li>', '<li>Remojar las lentejas en agua fría durante 8 hrs.</li><br>\r\n\r\n<li>Cortar el chorizo colorado en rodajas. Poner los trozos de chorizo en una olla con agua y hervir durante 15 minutos, esto va a generar que el chorizo se desgrase y evitaremos que el guiso quede con mucho aceite.</li><br>\r\n\r\n<li>Cortar la panceta en pedacitos pequeños. Reservar.</li><br>\r\n\r\n<li>Cortar la cebolla, el morrón y el ajo de manera que quede bien picado. Luego cortar las papas en cubos y reservar.</li><br>\r\n\r\n<li>Colocar en una olla anti-adherente y a fuego fuerte los pedacitos de panceta. No tocar por 5 minutos y luego comenzar a revolver despacio, la idea es que la panceta quede bien crocante hasta dorar. Reservar. De la misma manera cocinar el chorizo a fuego fuerte hasta dorar.</li><br>\r\n\r\n<li>Logrado esto, sumar la cebolla, el morrón y el ajo. Añadir un poquito de sal para que las verduras larguen su agua y queden bien tiernas. Cocinar hasta que la cebolla esté transparente.</li><br>\r\n\r\n<li>Sumar el tomate triturado a la olla y condimentar con sal, pimienta, ají en polvo, pimentón, y una pizca de orégano.</li><br>\r\n\r\n<li>Por último sumar las lentejas, las papas y agregar agua hasta cubrirlas. Agregar el laurel y revolver.</li><br>\r\n\r\n<li>Tapar la olla y cocinar a fuego medio, cada tanto abrir la olla y revolver, procurando que el agua cubra las lentejas en todo momento. Cocinar por 20 minutos.</li><br>\r\n\r\n<li>Una vez que estén las lentejas cocidas a servir y disfrutar!</li>');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `users`
--

DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `username` varchar(30) NOT NULL,
  `password` varchar(60) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb3;

--
-- Volcado de datos para la tabla `users`
--

INSERT INTO `users` (`ID`, `username`, `password`) VALUES
(1, 'Alan', '81dc9bdb52d04dc20036dbd8313ed055'),
(2, 'Micaela', '81dc9bdb52d04dc20036dbd8313ed055'),
(3, 'Flavia', '81dc9bdb52d04dc20036dbd8313ed055');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
